version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app/web"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "chore"
  - package-ecosystem: "pip"
    directory: "/app/video-processing/lambda"
    target-branch: "develop"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "chore"
