version: "3"

services:
  privacypal:
    image: ghcr.io/cosc-499-w2023/privacypal:0.1.0-dev
    build: ../../web/
    user: "0"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - backend
    hostname: privacypal
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_DEFAULT_REGION: ca-central-1
      PRIVACYPAL_CONFIG_DIR: /opt/privacypal/
      PRIVACYPAL_INPUT_VIDEO_DIR: /opt/privacypal/input-videos
      PRIVACYPAL_OUTPUT_VIDEO_DIR: /opt/privacypal/output-videos
      NEXTAUTH_SECRET: a-very-secure-one
      NEXTAUTH_URL: http://localhost:8080
      DATABASE_URL: postgresql://privacypal:password@db:5432/privacypal
    volumes:
      - output_videos:/opt/privacypal/output-videos
      - input_videos:/opt/privacypal/input-videos
      # - ../../web/conf/user.properties.json:/opt/privacypal/user.properties.json:z
    restart: unless-stopped

  video-processor:
    image: ghcr.io/cosc-499-w2023/privacypal-vidprocess:0.1.0-dev
    build: ../../video-processing
    user: "0"
    networks:
      - backend
    hostname: video-processor
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_DEFAULT_REGION: ca-central-1
      PRIVACYPAL_CONFIG_DIR: /opt/privacypal/
      PRIVACYPAL_INPUT_VIDEO_DIR: /opt/privacypal/input-videos
      PRIVACYPAL_OUTPUT_VIDEO_DIR: /opt/privacypal/output-videos
    volumes:
      - output_videos:/opt/privacypal/output-videos
      - input_videos:/opt/privacypal/input-videos
    restart: unless-stopped

networks:
  backend:

volumes:
  output_videos:
    driver: local
  input_videos:
    driver: local
