version: "3"

services:
  privacypal:
    image: ghcr.io/cosc-499-w2023/privacypal:0.1.0-dev
    build: ../../front-end/
    user: "0"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - backend
    hostname: privacypal
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_DEFAULT_REGION: ca-central-1
      PRIVACYPAL_CONFIG_DIR: /opt/privacypal/
      PRIVACYPAL_INPUT_VIDEO_DIR: /opt/privacypal/input-videos
      PRIVACYPAL_OUTPUT_VIDEO_DIR: /opt/privacypal/output-videos
      NEXTAUTH_SECRET: a-very-secure-one
      NEXTAUTH_URL: http://localhost:8080
      DATABASE_URL: postgresql://privacypal:a_secure_password@db:5432/privacypal
    volumes:
      - output_videos:/opt/privacypal/output-videos
      - input_videos:/opt/privacypal/input-videos
      # - ../../front-end/conf/user.properties.json:/opt/privacypal/user.properties.json:z
    restart: unless-stopped

  video-processor:
    image: ghcr.io/cosc-499-w2023/privacypal-vidprocess:0.1.0-dev
    build: ../../back-end/video-processing
    user: "0"
    networks:
      - backend
    hostname: video-processor
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_DEFAULT_REGION: ca-central-1
      PRIVACYPAL_CONFIG_DIR: /opt/privacypal/
      PRIVACYPAL_INPUT_VIDEO_DIR: /opt/privacypal/input-videos
      PRIVACYPAL_OUTPUT_VIDEO_DIR: /opt/privacypal/output-videos
    volumes:
      - output_videos:/opt/privacypal/output-videos
      - input_videos:/opt/privacypal/input-videos
    restart: unless-stopped

  db:
    image: docker.io/library/postgres:16-bullseye
    networks:
      - backend
      - db-admin
    hostname: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: privacypal
      POSTGRES_USER: privacypal
      POSTGRES_PASSWORD: a_secure_password
    volumes:
      - postgres:/var/lib/pgsql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U privacypal -d privacypal || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

  db-init:
    image: ghcr.io/cosc-499-w2023/privacypal-init-db:0.1.0-dev
    depends_on:
      db:
        condition: service_healthy
    build: ../../front-end/db
    networks:
      - db-admin
    environment:
      DATABASE_URL: postgresql://privacypal:a_secure_password@db:5432/privacypal

  db-viewer:
    image: docker.io/dpage/pgadmin4:7
    depends_on:
      db:
        condition: service_healthy
    hostname: db-viewer
    ports:
      - "8989:8989"
    networks:
      - db-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@privacypal.io
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8989
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./include/servers.json:/pgadmin4/servers.json:z
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8989 || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s

networks:
  backend:
  db-admin:

volumes:
  output_videos:
    driver: local
  input_videos:
    driver: local
  postgres:
    driver: local
  pgadmin:
    driver: local
