version: "3"

services:
    privacypal:
        image: ghcr.io/cosc-499-w2023/privacypal:0.1.0-dev
        build: ../../web/
        pull_policy: build
        depends_on:
            db-init:
                condition: service_completed_successfully
        networks:
            - backend
        hostname: privacypal
        expose:
            - 8080
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
            AWS_CLIENT: ${AWS_CLIENT}
            AWS_CLIENT_SECRET: ${AWS_CLIENT_SECRET}
            AWS_POOL_ID: ${AWS_POOL_ID}
            AWS_REGION: ca-central-1
            PRIVACYPAL_CONFIG_DIR: /opt/privacypal/
            PRIVACYPAL_AUTH_MANAGER: cognito
            PRIVACYPAL_DEBUG: "true"
            PRIVACYPAL_AUTH_SECRET: NZFbGxlrFl5Ae2kh0pcKbsiNVL37eEvtSg4zunBpfmw=
            PRIVACYPAL_COOKIE_NAME: privacypal
            PRIVACYPAL_LAMBDA_NAME: processVideoContainer
            PRIVACYPAL_OUTPUT_BUCKET: privacypal-output
            PRIVACYPAL_TMP_BUCKET: privacypal-input
            NEXTAUTH_URL: http://localhost:8080
            NEXTAUTH_SECRET: wp9CNmEFfrfAAE46zJzWTUGzpzOvIbwj/P7Hs9E9i9s=
            DATABASE_URL: postgresql://privacypal:password@db:5432/privacypal
        restart: unless-stopped

networks:
    backend:
