{{ $fullName := include "privacypal.fullname" . -}}
{{- if empty .Values.database.credentialSecretName -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-postgres-secret
  labels:
    {{- include "privacypal.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ include "privacypal.databasePassword" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-nextauth-secret
  labels:
    {{- include "privacypal.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET: {{ include "privacypal.nextauthSecret" . }}
