{{- $svcName := include "privacypal.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "privacypal.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.web.service.annotations | indent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "privacypal.selectorLabels" . | nindent 4 }}
