name: Container image build

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "develop"
      - "master"
      - "main"
  workflow_dispatch:

env:
  AWS_REGION: ca-central-1
  OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/Release.key"
  OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04"

permissions:
  packages: write
  contents: read
  id-token: write # Required for requesting the JWT

jobs:
  build-web:
    name: Build web server image
    runs-on: ubuntu-latest
    steps:
    - name: Install podman v4
      run: |
        echo "deb $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
        curl -fsSL $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
        sudo apt -y purge podman
        sudo apt update && sudo apt -y install podman
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build web server image
      working-directory: app/web
      run: | 
        IMAGE_NAMESPACE="${{ secrets.AWS_ECR_REPO_BASE }}" make oci-build
    - name: Get image tag
      id: get-image-tag
      working-directory: app/web
      run: |
        IMG_TAG="$(make --eval='print-img-ver: ; @echo $(IMAGE_VERSION)' print-img-ver)"
        echo "tags=$IMG_TAG" >> $GITHUB_OUTPUT
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true
    - name: Push to AWS ECR
      id: push-to-ecr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: privacypal
        tags: ${{ steps.get-image-tag.outputs.tags }}
        registry: ${{ secrets.AWS_ECR_REPO_BASE }}

  build-video-processor-lambda:
    name: Build video processing Lambda image
    runs-on: ubuntu-latest
    steps:
    - name: Install podman v4
      run: |
        echo "deb $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
        curl -fsSL $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
        sudo apt -y purge podman
        sudo apt update && sudo apt -y install podman
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build video processor Lambda image
      working-directory: app/video-processing
      run: |
        IMAGE_NAMESPACE="${{ secrets.AWS_ECR_REPO_BASE }}" make lambda-oci-build
    - name: Get image tag
      id: get-image-tag
      working-directory: app/video-processing
      run: |
        IMG_TAG="$(make --eval='print-img-ver: ; @echo $(IMAGE_VERSION)' print-img-ver)"
        echo "tags=$IMG_TAG" >> $GITHUB_OUTPUT
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true
    - name: Push to AWS ECR
      id: push-to-ecr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: privacypal-vidproc-lambda
        tags: ${{ steps.get-image-tag.outputs.tags }}
        registry: ${{ secrets.AWS_ECR_REPO_BASE }}

  build-video-conversion-lambda:
    name: Build video conversion Lambda image
    runs-on: ubuntu-latest
    steps:
    - name: Install podman v4
      run: |
        echo "deb $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
        curl -fsSL $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
        sudo apt -y purge podman
        sudo apt update && sudo apt -y install podman
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build video conversion Lambda image
      working-directory: app/video-conversion
      run: |
        IMAGE_NAMESPACE="${{ secrets.AWS_ECR_REPO_BASE }}" make lambda-oci-build
    - name: Get image tag
      id: get-image-tag
      working-directory: app/video-conversion
      run: |
        IMG_TAG="$(make --eval='print-img-ver: ; @echo $(IMAGE_VERSION)' print-img-ver)"
        echo "tags=$IMG_TAG" >> $GITHUB_OUTPUT
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true
    - name: Push to AWS ECR
      id: push-to-ecr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: privacypal-vidconvert-lambda
        tags: ${{ steps.get-image-tag.outputs.tags }}
        registry: ${{ secrets.AWS_ECR_REPO_BASE }}

  build-db-init:
    name: Build database initialize image
    runs-on: ubuntu-latest
    steps:
    - name: Install podman v4
      run: |
        echo "deb $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_SOURCE_URL/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
        curl -fsSL $OPENSUSE_UNOFFICIAL_LIBCONTAINERS_KEY_URL | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
        sudo apt -y purge podman
        sudo apt update && sudo apt -y install podman
    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build database init image
      working-directory: app/web/db
      run: |
        IMAGE_NAMESPACE="${{ secrets.AWS_ECR_REPO_BASE }}" make oci-build
    - name: Get image tag
      id: get-image-tag
      working-directory: app/web/db
      run: |
        IMG_TAG="$(make --eval='print-img-ver: ; @echo $(IMAGE_VERSION)' print-img-ver)"
        echo "tags=$IMG_TAG" >> $GITHUB_OUTPUT
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true
    - name: Push to AWS ECR
      id: push-to-ecr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: privacypal-init-db
        tags: ${{ steps.get-image-tag.outputs.tags }}
        registry: ${{ secrets.AWS_ECR_REPO_BASE }}
