name: Database Initializer Unit Tests

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "develop"
      - "master"
      - "main"
  pull_request:
    paths:
      - "app/web/db/**"
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  itest:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Run tests
      working-directory: app/web/db
      run: make test
