name: NextJS Unit Tests

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "develop"
      - "master"
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Install dependencies
      run: cd app/web && npm ci
    - name: Run tests
      run: cd app/web && npm run test
