name: Video Processing Server Unit Tests

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "develop"
      - "master"
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Install dependencies
      run: pip install -r app/back-end/video-processing/requirements.txt
    - name: Run tests
      run: python3 -m unittest discover -s ./tests/back-end
