name: Video Processing Server Unit Tests

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "develop"
      - "master"
      - "main"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: '**/requirements*.txt'
    - name: Install dependencies
      working-directory: app/video-processing
      run: pip install -r requirements.txt -r requirements_dev.txt
    - name: Run tests
      working-directory: app/video-processing
      run: make test
